LIB = $(CURDIR).a

OBJS = \
      uphistrange.o\
      uppydump.o\
      uppyfact.o\
      uppyfill.o\
      pybookinit.o

$(LIB): $(LIB)($(OBJS))

clean:
	$(RM) $(OBJS)

distclean: clean
	$(RM) $(LIB)

