LIB = $(CURDIR).a

OBJS = \
      upclosepyfile.o\
      upclosegradefile.o\
      updatafile.o\
      uplogo.o\
      upopenfile.o\
      vegaslogo.o\

$(LIB): $(LIB)($(OBJS))

clean distclean:
	$(RM) $(OBJS) $(LIB)

